#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP-1 -d 1 2 3 4 5 
bspc monitor HDMI-1 -d 6 7 8 9 10 
bspc monitor eDP-1 --swap HDMI-1

bspc config border_width         2
bspc config window_gap           3

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

polybar principal &
$HOME/.config/bspwm/autoMonitors.sh
feh --bg-scale $HOME/paper.*
setxkbmap -option grp:alt_shift_toggle us,latam &
xfce4-power-manager
picom &
